genre = ['Adventure', 'Puzzle', 'Role-playing', 'Simulation', 'Strategy', 'Sports', 'MMO', 'Sandbox', 'Moba', 'Action RPG', 'MMORPG'\
    , 'Roguelike', 'Role playing' , 'Platformer', 'Shooter', 'Fighting', 'Survival', 'Rhythm', 'Battle Royale', 'Action Adventure']

game_data = [
    ['Sandbox', 'Minecraft', 10]
    ['Battle Royale', 'Fortnite', 12]
    ['Shooter', 'Counter-Strike: Global Offensive', 18]
    ['Simulation', 'The Sims 4', 13]
    ['Shooter', 'Call of Duty: Modern Warfare II', 17]
    ['MMO', 'Roblox', 13]
    ['Moba', 'League of Legends', 13]
    ['Moba', 'Dota 2', 13]
    ['Shooter', 'Valorant', 16]
    ['Action Adventure', 'Grand Theft Auto V', 18]
    ['Sports', 'Rocket League', 3]
    ['Sports', 'Fifa 23', 3]
    ['Shooter', 'Destiny 2', 13]
    ['Battle Royale', 'Apex Legends', 16]
    ['Shooter', 'Tom Clancys Rainbow Six: Siege', 18]
    ['Shooter', 'Battlefield 2024', 17]
    ['Action RPG', 'Genshin Impact', 12]
    ['Battle Royale', 'Fall Guys', 3]
    ['Platformer', 'Only Up!', 13]
    ['Platformer', 'Ori and the Blind Forest', 8]
    ['Action RPG', 'Nier Automata', 18]
    ['Role playing', "Baldur's Gate III", 18]
    ['Role playing', 'Divinity II Original Sin', 18]
    ['Action RPG', 'Cyberpunk 2077', 18]
    ['Simulation', 'Dinkum', 12]
    ['Action RPG', 'Final Fantasy VII Remake Intergrade', 16]
    ['Action RPG', 'Final Fantasy XVI', 18]
    ['MMORPG', 'Final Fantasy XIV', 13]
    ['MMORPG', 'World Of Warcraft', 12]
    ['MMORPG', 'New World', 13]
    ['MMORPG', 'Elder Scrolls Online', 18]
    ['Action RPG', 'Elder Scrolls Skyrim', 18]
    ['Roguelike', 'Gunfire Reborn', 10]
    ['Survival', 'Icarus', 12]
    ['Role Playing', 'Ruined King: A League of Legends Story', 16]
    ['Battle Royale', 'PUBG: Battlegrounds', 16]
    ['Adventure', 'Dave the Diver', 13]
    ['Survival', 'Rust', 18]
    ['Action Adventure', 'Red Dead Redemption 2', 18]
    ['Survial', 'Project Zomboid', 13]
    ['Simulation', 'Forza Horizon 5', 5]
    ['Survival', 'Dead by Daylight', 12]
    ['Survival', 'Dayz', 18]
    ['Simulation', 'Euro Truck Simulator 2', 10]
    ['Roguelike', 'The Binding of Isaac: Rebirth', 9]
    ['Sandbox', 'Terraria', 12]
    ['Simulation', 'Stardew Valley', 12]
    ['Strategy', 'Crusader Kings III', 12]
    ['Strategy', 'Total War: Warhammer III', ]
    ['Strategy', 'Age of Empires IV', ]
    ['Simulation', 'Microsoft Flight Simulator 40th Anniversary Edition', ]
    ['Roguelike', 'Hades', ]
    ['Simulation', 'Cities: Skylines', ]
    ['Fighting', 'Street Fighter 6', ]
    ['Puzzle', 'A Little To The Left', ]
    ['Puzzle', 'Escape Simulator', ]
    ['Puzzle', 'The Room 4: Old Sins', ]
    ['Rhythm', 'Hi-Fi Rush', ]
    ['Rhythm', 'Muse Dash', ]
    ['Fighting', 'Mortal Kombat 11', ]
    ]